### ISSUE TITLE
Automated build failing when installing cryptography

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/docker-debian8-ansible#5]
Example (from: https://travis-ci.org/geerlingguy/docker-debian8-ansible/builds/291270125):

```
Step 6/9 : RUN pip install ansible cryptography
 ---> Running in 956a7f273ea4
Downloading/unpacking ansible
 Running setup.py (path:/tmp/pip-build-Vtb20J/ansible/setup.py) egg_info for package ansible
 no previously-included directories found matching 'ticket_stubs'
 no previously-included directories found matching 'hacking'
 'test/integration/targets/unarchive/files/test-unarchive-nonascii-くらとみ.tar.gz' not ANSI_X3.4-1968 encodable -- skipping
Downloading/unpacking cryptography
 Running setup.py (path:/tmp/pip-build-Vtb20J/cryptography/setup.py) egg_info for package cryptography
 error in cryptography setup command: Invalid environment marker: python_version < '3'
 Complete output from command python setup.py egg_info:
 error in cryptography setup command: Invalid environment marker: python_version < '3'
----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-Vtb20J/cryptography
Traceback (most recent call last):
 File "/usr/bin/pip", line 9, in <module>
 load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
 File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 248, in main
 return command.main(cmd_args)
 File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
 text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 70: ordinal not in range(128)
The command '/bin/sh -c pip install ansible cryptography' returned a non-zero code: 1
```

I can reproduce the error locally and when run via the Docker Hub automated image build.

**Comment by geerlingguy** [comment]
Related to #2, most likely.

**Comment by geerlingguy** [comment]
The fix—upgrade setuptools: https://github.com/ansible/ansible/issues/31741#issuecomment-337745346
