### ISSUE TITLE
Build failing while running cryptography/setup.py

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/docker-debian8-ansible#8]
```
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-QGgXAV/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-lF0UHz-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-QGgXAV/cryptography
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 248, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 50: ordinal not in range(128)
The command '/bin/sh -c pip install --upgrade setuptools     && pip install $pip_packages' returned a non-zero code: 1
The command "docker build -t docker-ansible ." exited with 1.
```

From build: https://travis-ci.org/geerlingguy/docker-debian8-ansible/builds/616404014

**Comment by geerlingguy** [comment]
The current version of the image which was built successfully 14 days ago is running `cryptography===2.8`, so I just tried installing that by itself, and _that_ didn't work.

Could something in upstream Debian 8 packaging for `python-dev` or `python-pip` have broken things? I also am seeing:

```
  Running setup.py install for cryptography
    WARNING: The wheel package is not available.
    
    Usage:
      /usr/bin/python -m pip <command> [options]
    
    no such option: --disable-pip-version-check
```

Whereas before I never saw the 'wheel' notice.

**Comment by geerlingguy** [comment]
It _seems_ that all that's required is upgrading Pip (`pip install --upgrade pip setuptools`). Pip was at like version 1.5.x while the latest version is 19.x...

**Comment by geerlingguy** [comment]
Strangely, I also had to explicitly install `wheel cryptography ansible` in my `pip install` command, otherwise it would fail.
